# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RunwaysClassifier
                                 A QGIS plugin
 This plugin classifying runways types based on their patterns 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-04-25
        copyright            : (C) 2019 by Jenya Brodski
        email                : jekab596@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RunwaysClassifier class from file RunwaysClassifier.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .runways_classifier import RunwaysClassifier
    return RunwaysClassifier(iface)
