# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ImageIterator
                                 A QGIS plugin
 This plugin classifying runways types based on their patterns
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-04-25
        git sha              : $Format:%H$
        copyright            : (C) 2019 by Jenya Brodski
        email                : jekab596@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

class ImageIterator:
    """
    Iterate on data given about airports
    """
    def __init__(self, data):
        """
        Constructor

        :param data:
        """
        self.data = data

    def __getitem__(self, i):
        """ 
        get the next item 
        
        :param i:

        :return: data in the i position
        :rtype: list
        """
        return self.data[i]

    def __iter__(self):
        self.i = 0
        return self

    def __next__(self):
        """
        get the next item

        :return: item
        """
        
        if self.i == len(self.data):
            raise StopIteration
        item = self.data[self.i]
        self.i += 1
        return item

    def getIndex(self):
        """
        :return: index
        :rtype: int
        """

        return self.i - 1


